Repository MergejilProject/Mergejil, pull requests merged in 2023-05, with the labels that each got.

#57 homeINformation hiisn
  frontend/mergejil/src/App.jsx
  frontend/mergejil/src/components/homeInformation.jsx
  frontend/mergejil/src/components/navbar.jsx
  frontend/mergejil/src/styles/homeInformation.css
Labels: documentation

#62 a
  frontend/mergejil/src/App.jsx
  frontend/mergejil/src/pages/CoursePage.jsx
  frontend/mergejil/src/pages/SignUpPage.jsx
  frontend/mergejil/src/styles/coursePage.css
  frontend/mergejil/src/styles/signUpPage.css
Labels: documentation

#66 mergejilHeaderHiisn
  frontend/mergejil/src/App.jsx
  frontend/mergejil/src/components/mergejilHeader.jsx
  frontend/mergejil/src/styles/mergejilHeader.css
  frontend/mergejil/tailwind.config.js
Labels: documentation

#68 professionPage ehelsn
  frontend/mergejil/src/App.jsx
  frontend/mergejil/src/pages/CoursePage.jsx
  frontend/mergejil/src/pages/ProfessionPage.jsx
  frontend/mergejil/src/styles/ProfessionPage.css
  frontend/mergejil/src/styles/footer.css
Labels: documentation

#72 about us own page hiijga dutuu bgaa
  frontend/mergejil/package-lock.json
  frontend/mergejil/package.json
  frontend/mergejil/src/App.jsx
  frontend/mergejil/src/components/AboutUsIntroduce.jsx
  frontend/mergejil/src/components/AboutUsOwnPage.jsx
  frontend/mergejil/src/styles/AboutUsIntroduce.css
  frontend/mergejil/src/styles/AboutUsOwnPage.css
Labels: bug

#73 contact page duussn
  frontend/mergejil/package-lock.json
  frontend/mergejil/package.json
  frontend/mergejil/postcss.config.js
  frontend/mergejil/src/App.jsx
  frontend/mergejil/src/index.js
  frontend/mergejil/src/pages/ContactPage.jsx
  frontend/mergejil/src/styles/ContactPage.css
  frontend/mergejil/tailwind.config.js
Labels: duplicate
