Repository MergejilProject/Mergejil, pull requests merged in 2023-04, with the labels that each got.

#20 navbarEhelsn
  frontend/mergejil/package-lock.json
  frontend/mergejil/package.json
  frontend/mergejil/src/App.css
  frontend/mergejil/src/App.js
  frontend/mergejil/src/App.jsx
  frontend/mergejil/src/App.test.js
  frontend/mergejil/src/components/navbar.jsx
  frontend/mergejil/src/index.css
  frontend/mergejil/src/index.js
  frontend/mergejil/src/logo.svg
  frontend/mergejil/src/reportWebVitals.js
  frontend/mergejil/src/setupTests.js
  frontend/mergejil/src/styles/navbar.css
Labels: documentation

#21 user backend ehlsn yrn duussn
  backend/controller/user.js
  backend/index.js
  backend/model/User.js
  backend/router/user.js
Labels: enhancement

#24 hashpassword hiisn
  backend/controller/authorization.js
  backend/controller/user.js
  backend/index.js
  backend/middleware/middleware.js
  backend/model/Authorization.js
  backend/model/User.js
  backend/package-lock.json
  backend/package.json
  backend/router/authorization.js
Labels: bug

#26 sectionHiisen
  frontend/mergejil/src/App.jsx
  frontend/mergejil/src/components/overlay.jsx
  frontend/mergejil/src/components/section.jsx
  frontend/mergejil/src/styles/overlay.css
  frontend/mergejil/src/styles/section.css
Labels: documentation

#31 instructorpage brg dussn
  frontend/mergejil/package-lock.json
  frontend/mergejil/package.json
  frontend/mergejil/src/App.jsx
  frontend/mergejil/src/pages/InstracturPage.jsx
  frontend/mergejil/src/styles/instructar.css
Labels: good first issue

#33 testimonials backcrup hiisn
  backend/controller/homeTestimonials.js
  backend/controller/user.js
  backend/index.js
  backend/model/HomeTestimonials.js
  backend/router/homeTestimonials.js
Labels: good first issue

#35 paginetion hisn
  backend/controller/instructor.js
Labels: documentation, help wanted

#37 testimonial ehluulsn
  frontend/mergejil/src/App.jsx
  frontend/mergejil/src/components/testimonial.jsx
  frontend/mergejil/src/styles/testimonial.css
Labels: documentation

#41 app.jsx deer garsan conflict zassan
  frontend/mergejil/src/App.jsx
Labels: bug

#43 halit ehlsn recentPost
  frontend/mergejil/src/App.jsx
  frontend/mergejil/src/components/recentPost.jsx
  frontend/mergejil/src/styles/recentPost.css
Labels: documentation

#48 footer hiisen
  frontend/mergejil/src/App.jsx
  frontend/mergejil/src/components/Footer.jsx
  frontend/mergejil/src/styles/footer.css
Labels: enhancement

#50 infoSidebar hiisen
  frontend/mergejil/src/App.jsx
  frontend/mergejil/src/components/InformationSidebar.jsx
  frontend/mergejil/src/styles/informationSidebar.css
Labels: enhancement
